import requests ,os
# server酱开关，填0不开启(默认)，填2同时开启cookie失效通知和签到成功通知
sever = '2'
# 填写server酱sckey,不开启server酱则不用填（自己更改）
sckey = 'SCU139493Tdaddc3938db2222568fcc54fe0b1def05fe728b332788'
# 填入glados账号对应cookie
cookie = '_octo=GH1.1.382650631.1612787978; _device_id=b2c8e6ffea64f8538abcda0385756f63; user_session=zLlg-YxTZ5WYG8dlIOg2jppnmx8FAW9YmoUV2ZthMhC7Dfgr; __Host-user_session_same_site=zLlg-YxTZ5WYG8dlIOg2jppnmx8FAW9YmoUV2ZthMhC7Dfgr; logged_in=yes; dotcom_user=GitDjAr; has_recent_activity=1; color_mode=%7B%22color_mode%22%3A%22light%22%2C%22light_theme%22%3A%7B%22name%22%3A%22light%22%2C%22color_mode%22%3A%22light%22%7D%2C%22dark_theme%22%3A%7B%22name%22%3A%22dark%22%2C%22color_mode%22%3A%22dark%22%7D%7D; tz=Asia%2FShanghai; _gh_sess=EK7F2mwzvbdW9kzvco85JDNii6xNg5vJk1I4%2BpNL737YwVXotEI3%2BE5sGTSDFzJIWrCH%2Bn9F1nz8Y4zc2cQYedNo58UtkNrzZSDQib24vThI7hSnn0sBJDpC6shFw0J6y4i3NLlgYxYbgqXaVTqVxN47ZETlTcmaECOV7mY60v%2Be3Nh%2Frn%2FhwWLDU6qAcjW50ja86ONoccDoc8YR1iDBqo940tnJQt8ZwZn3ad7elG87qbO9lGElF5MrJhm2mYq45W3ouA%3D%3D--QRwboXopyNeXxpmt--l0wvjkGcVj%2FVdomcCIHpnQ%3D%3D'
referer = 'https://glados.rocks/console/checkin'

def start():
    
    url= "https://glados.rocks/api/user/checkin"
    url2= "https://glados.rocks/api/user/status"
    origin = "https://glados.rocks"
    referer = "https://glados.rocks/console/checkin"
    useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
    payload={
        'token': 'glados_network'
    }
    checkin = requests.post(url,headers={'cookie': cookie ,'referer': referer,'origin':origin,'user-agent':useragent,'content-type':'application/json;charset=UTF-8'},data=json.dumps(payload))
    state =  requests.get(url2,headers={'cookie': cookie ,'referer': referer,'origin':origin,'user-agent':useragent})
   # print(res)

    if 'message' in checkin.text:
        mess = checkin.json()['message']
        time = state.json()['data']['leftDays']
        time = time.split('.')[0]
        #print(time)
        if sever == 'on':
            requests.get('https://sc.ftqq.com/' + sckey + '.send?text='+mess+'，you have '+time+' days left')
    else:
        requests.get('https://sc.ftqq.com/' + sckey + '.send?text=cookie过期')

def main_handler(event, context):
  return start()

if __name__ == '__main__':
  start()
